### ISSUE TITLE
Skewed page layout at /fundamentals/principles/?hl=ru

### ISSUE THREAD

**Issue by denpatin** [google/WebFundamentals#1070]
The layout of one section, when reading in [Russian](https://developers.google.com/web/fundamentals/principles/?hl=ru), got skewed because of an exceedingly multiline title.
![screen shot 2015-01-04 at 10 32 41 pm](https://cloud.githubusercontent.com/assets/1271040/5607193/b88c0dd6-9461-11e4-84e3-ffcbaa365b1b.png)

The same section in [English](https://developers.google.com/web/fundamentals/principles/?hl=en) looks perfect:
![screen shot 2015-01-04 at 10 33 00 pm](https://cloud.githubusercontent.com/assets/1271040/5607194/bcb2a2ee-9461-11e4-9ebd-6080dc74d7db.png)

**Comment by PaulKinlan** [comment]
Urgh,  Not sure how we are going to deal with this as there is a max
height.... Will have a think.

**Comment by yuzver** [comment]
if rename "Домашняя страница и навигация по сайту" to "Главная страница" and "Интерактивные формы" to "Удобные формы" - all will be nice. How you think?

**Comment by denpatin** [comment]
@yuzver Are you sure there is a need to change the title of "Интерактивные формы"? The layout there is fine. Reducing the line to just "домашняя страница" is a bit rash because in this section menus are as well considered as the home page structure. Maybe "Домашняя страница и меню" could be a remedy?

**Comment by yuzver** [comment]
@denpatin, according to my feelings: easier to cut two long title, which below is a description of the topic. Not the way to translate literally(!) from English or to change specifically the partition layout because of the long headers;) 

- Главная страница и меню: http://screencast.com/t/bZEOTgoyCbZx
- Главная странца: http://screencast.com/t/0swPQD3gZfl
Section is devoted clearly the main page, so the extra mentioning about navigation I seem superfluous.

- Интерактивные формы: http://screencast.com/t/or0qmzPQvqoU
- Удобные формы: http://screencast.com/t/3m6e6HYgEL2
"icon-lessons" zooming in on the text and it doesn't look good. Or it's ok?

**Comment by denpatin** [comment]
@yuzver Only "главная страница" looks, of course, more pleasant to eyes. However the meaning of this title is not full.

As for "удобные формы", I cannot say the word "удобный" anyhow correlates with "интерактивный". Moreover, on the same level with "интерактивные формы" there is a two-line title so I do believe there is no need in the change.

**Comment by petele** [comment]
I believe this is now fixed.
