### ISSUE TITLE
Feedback for: mobile compatibility

### ISSUE THREAD

**Issue by ArtistScope** [google/WebFundamentals#1087]
I received an email from Google claiming that 86 of my web pages are not mobile compatible. Sorry but we design web services for use on computers and not amusement devices. Also:

1. How does Google have the audacity to decide good web design when they have never been able to provide a web browser that properly complies with acceptable web standards?

2. If web pages do not work in Google phones then perhaps they should fix their adhoc amusement devices first!

3. This Web Fundamentals service provides NO clue as to what good mobile design is anyway... instead it only serves as more spamvertising.

4. Please get real. The Internet has been and will be here forever. It's time that Google started to comply to its standards instead of pretending to be an authority on anything other than "advertising" and hacking things to suit their own monetisation scheme.

**Comment by PaulKinlan** [comment]
Thanks for the message. I think users and the industry generally disagree with your statement about mobile being amusement devices. Web traffic has been moving mobile for a long time now and represents a significant proportion of total traffic and developers need to be able to understand how to create web sites and apps that work across all form-factors.

Web Fundamentals has been received pretty well, but certainly can be improved.  We would love to hear specific issues that you have with it so that we can address them.  Please file individual bugs so that I can work with my team to get them addressed.

We do have a section at the moment about monetization that we are expanding to include more information about how developers can optimize user conversions and revenue through any means and not just advertising.

With regards to your 86 sites, if they are only optimized for desktop we (Google) don't put a "Mobile friendly" badge in search results when a user is searching on a mobile device.  I think this is fair, and the tools we provide on this site are to help you give the best experience for users on any device.  

Happy to help you look at your sites to see if there is anything to improve for mobile users (there might not be).
