### ISSUE TITLE
[EN] Feedback for: /fundamentals/index.html

### ISSUE THREAD

**Issue by bobgasink** [google/WebFundamentals#1173]
Way too many "mobile" versions of applications are dumbed-down and nearly useless.  Often there is so little screen left between big sloppy borders that it's like looking at the world through a mail slot.   THIS WHOLE GOOGLE POLICY IS MISGUIDED!!!!!

**Comment by PaulKinlan** [comment]
Its based on where the users are. If you are on mobile you expect a good
mobile experience from search and the sites it recommends.

**Comment by bobgasink** [comment]
Google is in the search business.  Web developers are in the web
    development business.  Google search should not be forcing web
    developers to modify sites in ways that make them less useful.  Let
    mobile users decide what constitutes a "good mobile experience".
    
    
      
        Thanks!
        --Bob
        
        
      
    On 3/22/2015 11:30 AM, Paul Kinlan
      wrote:
    
    Its based on where the users are. If you are on mobile
      you expect a good
      mobile experience from search and the sites it recommends.
      
      On Sun, 22 Mar 2015 15:18 bobgasink
      <notifications@github.com> wrote:
      
      > Way too many "mobile" versions of applications are
      dumbed-down and nearly
      > useless. Often there is so little screen left between big
      sloppy borders
      > that it's like looking at the world through a mail slot. THIS
      WHOLE GOOGLE
      > POLICY IS MISGUIDED!!!!!
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
      <https://github.com/google/WebFundamentals/issues/1173>.
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PaulKinlan** [comment]
We are saying users cant find content as well on non-optimised sites
therefore to keep our users happy we give add mobile-ness as a ranking
criteria.

Your impression that mobile sites hide content that desktop shows
highlights your lack of understanding about design for the web across form
factors.

If you only care about desktop users and traffic from search on desktop
dont change anything you are doing.

**Comment by phronimos** [comment]
On 3/22/2015 8:49 AM, bobgasink wrote:
>      Google is in the search business.  Web developers are in the web
>      development business.  Google search should not be forcing web
>      developers to modify sites in ways that make them less useful.  Let
>      mobile users decide what constitutes a "good mobile experience".

I am *so* pleased to see this question opened up again. I only joined 
GitHub the end of Jan. 2015 in order to comment on the issue at

https://github.com/google/WebFundamentals/issues/1087

but wasn't able to do so, since that thread had already been closed 
(which I hadn't realized, since I'm a newbie at this GitHub business).

Even though GitHub is described in the documentation as being for 
everyone, the learning curve is a bit steep, especially for those of 
us already working our tail feathers off as web developers, so I was 
just about to quit the GitHub community when several posts to this 
thread ("issue" ?), #1173, appeared in my mailbox.

This issue is important enough to me that I want now to take a moment 
to respond (or try to respond: please be patient as I figure out how 
all of this works ;-).

I too received an email from Google claiming that my web pages "have 
critical mobile usability errors" which will "severely affect how 
mobile users are able to experience your website"; hence, "These pages 
will not be seen as mobile-friendly by Google Search, and will 
therefore be displayed and ranked appropriately for smartphone users."

Like ArtistScope, who initiated the #1087 thread, and bobgasink who 
initiated this #1173 thread, I am very irritated with Google Search 
now setting itself up as the supreme arbiter concerning what is or is 
not good website design for mobile users.

In my case, there's the added rub that I have been trying for several 
years to get Google to even index the very website it now deems 
defective for mobile users. As of 3/15/2015 -- when I resubmitted my 
sitemap yet again to alert the Google bot that I had just added 
another new page to the site -- Google had indexed only 11 of the 38 
URLs previously submitted, despite the fact that this website contains 
some of the highest-quality content on the Web (my postdoctoral 
research that I have published nowhere else).

In Google's manual on Web design fundamentals, to which I was directed 
by the e-mail received via webmaster tools, I read that

	"Content is the most important aspect of any site. So let’s
	design for the content and not let the design dictate the
	content. In this guide, we identify the content we need
	first, create a page structure based on this content, and
	then present the page in a simple linear layout that works
	well on narrow and wide viewports."
< 
https://developers.google.com/web/fundamentals/getting-started/your-first-multi-screen-site/content 
 >, as viewed on 1/26/2015

But the reality is quite different: when I *do* let content dictate 
design, as at this website, I am penalized for it. In my experience, 
the big search engine algorithms still can't tell quality content from 
garbage content unless it fits neatly into their technocentric model. 
This model was already ill-suited to the kinds of non-commercial 
websites I create -- experimental scholarly hybrids which embrace the 
"emerging Wild West in academic publishing" and, in so doing, break 
almost every rule of best-practices SEO. But Google's latest design 
model, introducing a one-size-fits-all standard of "Mobile Usability", 
is even more irrelevant to my kind of scholarly content.

E.g., the 3 "critical mobile usability errors" for which my 3 website 
pages at

http://roses.communicatingbydesign.com/news/RosesNews.html

http://roses.communicatingbydesign.com/ToC.html

http://roses.communicatingbydesign.com/FYI_cancer-and-the-retail-economy.html

were cited are:

	1. Touch elements too close.
	2. Viewport not configured.
	3. Small font size.

This is ridiculous. If visitors using mobile phones can't be bothered 
"to double-tap or pinch-to-zoom in order to be able to see and 
interact with the content" -- which, at this website, is made freely 
available to all, as a public service -- I don't see why I should be 
at the added bother and expense of having to cater to them.

There are plenty of other visitors who value this website's original 
content enough to put up with far more important usability problems 
than these.

And ArtistScope raised another relevant concern in the earlier #1087 
thread:

	"How does Google have the audacity to decide good web design
	when they have never been able to provide a web browser that
	properly complies with acceptable web standards?"

I couldn't agree more, and have recently documented one instance of 
this in a report temporarily located at:

http://she-philosopher.org/home/technical/BrowserProblems.html

(currently configured as a beta test site, ergo off-limits to the big 
commercial search engines by way of robots.txt exclusions ... which 
don't seem to stop the bots from roaming all over the site anyway -- 
presumably because, in this case, I've asked them not to! ;-).

Thankfully, I've reached the point where I no longer care whether 
Google's search-engine shenanigans consign my content to oblivion, or not.

But I object strenuously when Google Search -- which has proven 
incapable of evaluating the quality of my scholarly content or its 
design -- now sets itself up as an impartial judge of a "good mobile 
experience."

Deborah

**Comment by PaulKinlan** [comment]
@phronimos this is the problem, the lack of understanding of why it is important to cater for users across all form factors.  You are forcing users to zoom in on your content on a mobile device.  Google search has always been about giving users the best result at the best time, and if users can't easily read your content, it is not the best result.  You mention

1. Touch elements too close.
2. Viewport not configured.
3. Small font size.

These are 3 issues that users on mobile hate the most. Content that they are forced to pan around on and zoom, content they can't read correctly due to font sizing issues and links that they can't click.  Un-happy users means less time on site, less click's through to other content and less chance they will convert (if you take payments).

Just to reiterate, if you don't want to make your content work well on mobile, that is perfectly fine.  The search changes only affect your site for users who are using mobile devices (which is a huge number).

**Comment by bobgasink** [comment]
Google's intent to punish websites by interfering with their search
    results because of stylistic site choices is an abuse of Google's
    gorilla position in the industry.  A web application that pinches
    and pans properly can allow mobile users complete access to the site
    and still permit the use of all the available screen inches.  It
    also gives developers one less interface to design, build, and
    debug, as well as one less interface for users to learn.  
    
    Just to reiterate, what users want is a common application interface
    that runs on desktops, tablets, and phones.  What they don't want is
    separate applications which have different, or harder to use, or
    dumbed-down oversimplified interfaces.
    
    The right way to solve the problem is by offering better mobile
    applications that win in the marketplace by superior user appeal,
    NOT by using Google search performance to bury competing application
    ideas.
    
    
      
        Thanks!
        --Bob
        
        
        
      
    On 3/22/2015 3:26 PM, Paul Kinlan
      wrote:
    
    
      @phronimos this is the problem, the
        lack of understanding of why it is important to cater for users
        across all form factors. You are forcing users to zoom in on
        your content on a mobile device. Google search has always been
        about giving users the best result at the best time, and if
        users can't easily read your content, it is not the best result.
        You mention
      
        Touch elements too close.
        Viewport not configured.
        Small font size.
      
      These are 3 issues that users on mobile hate the most. Content
        that they are forced to pan around on and zoom, content they
        can't read correctly due to font sizing issues and links that
        they can't click. Un-happy users means less time on site, less
        click's through to other content and less chance they will
        convert (if you take payments).
      Just to reiterate, if you don't want to make your content work
        well on mobile, that is perfectly fine. The search changes only
        affect your site for users who are using mobile devices (which
        is a huge number).
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by PaulKinlan** [comment]
I'm closing and locking this issue. You've demonstrated several times now that you don't understand the issues that user's face or even how to build sites that work across device form factors by stating: "What they don't want is separate applications which have different, or harder to use, or dumbed-down oversimplified interfaces." - this is exactly what we are not saying, you choose to think it is. 

Pinning multi-device issues down as a "stylistic site" is not what is happening in the industry nor what we are saying.  What you are saying is the equivalent of saying "I won't make my site accessible for screen readers because it's a stylistic choice"

> The right way to solve the problem is by offering better mobile applications that win in the marketplace by superior user appeal, NOT by using Google search performance to bury competing application    ideas.

*Sigh* You've just negated your previous arguments and thrown in a baseless accusation for the need to go mobile.
