### ISSUE TITLE
[IT] Feedback for: /fundamentals/getting-started/your-first-multi-screen-site/index.html

### ISSUE THREAD

**Issue by akikacnaig** [google/WebFundamentals#1237]
I'm Giancarlo, a quite old newby from Turin, Italy.
I tried to make my site device responsive, but the first doubt I have is that all docs (even yours) refers to "pix" parameter, instead of physical screen dimension.
For this reasons even your exampes doesn't pass in "mobile mode  (i.e style inside @media statement), because smartphone have more that 600pix , even if 4"...

Or do I miss something?

Thanks
![responsiveweb](https://cloud.githubusercontent.com/assets/12217706/7444281/518dc4d6-f17b-11e4-8e07-e9bb735b4ea9.jpg)

**Comment by phronimos** [comment]
On 5/3/2015 1:01 AM, akikacnaig wrote:
> Or do I miss something?

I've been wondering the very same thing for weeks now, and hope that 
somebody out there addresses Giancarlo's question.

FWIW, the more I look into (and actually try to implement) all of 
this, the more "doubts" (to borrow from Giancarlo ;-) I have.

I'm going to write up a detailed report with my findings and publish 
it at the website that Google Search has labeled mobile-unfriendly 
(since I have been told several times now that this is not the place 
for that kind of discussion ;-), but IMO, RWD "best practices," as 
specified in the Web Fundamentals guide, are not yet ready for prime time.

E.g., I was not a bit surprised to find this interesting essay 
acknowledging the continuing need for hybrid fixed+fluid layouts

http://webdesign.tutsplus.com/tutorials/the-role-of-table-layouts-in-responsive-web-design--webdesign-10294

since I, too, find floatL and floatR capabilities (as currently 
configured) inadequate substitutes for good old-fashioned tables, and 
just like many advertisers, I have a need for using fixed-width images.

So I can't help but think that it's premature for websites like mine 
to be investing heavily in redesigns which, as far as I can tell from 
the tests that I have run recently, do little to improve on my 
delivery of content.

On the upside, all the fuss over this Web Fundamentals guide and its 
recommendations has prompted me to make important design changes to my 
websites that in fact *do* improve on my information design and my 
delivery of content (especially for those using assistive 
technologies, who have less options for interacting with my content 
than do mobile-phone users) ... and so that's a good thing!

Truth be told, I'm not sure I would have forced myself to make these 
sorts of changes otherwise, since they're difficult to automate, and 
so painful to make by hand at a website with over 200,000 indexable 
words! ;-)

Deborah

**Comment by petele** [comment]
There are two types of px that web developers need to be aware of, by only one they really need to care about. 

Physical pixels - those are the number of hardware pixels your device has. For example, the iPhone 6+ is 1080 physical pixels wide, but 1920 physical pixels tall.
Device Independent Pixels or CSS Pixels - these are the number of pixels that the BROWSER reports as it's width. In the case of the iPhone 6+, it reports a width of 414px. 

When developing a responsive design, you should not consider the number of physical pixels, but instead only consider the number of CSS pixels. It's the one that defines how big the browser window should be.

Hope that helps!
