### ISSUE TITLE
DevTools Updates template is broken

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#1338]
Example: https://developers.google.com/web/updates/2015/05/19/cycle-through-editing-locations

Looks like the header and footer page isn't getting pulled into the final output for DevTools pages in updates.

**Comment by Meggin** [comment]
Yep. I noticed this but figured Paul B did this on purpose during io launch.

**Comment by gauntface** [comment]
Not sure why this would be on purpose :-S

**Comment by Meggin** [comment]
Yeah, I just was thinking that we were making the DevTools landing page
live at IO, so we didn't want the links to the unfinished docs there.
Instead it links to existing live docs.

It's super annoying for me too from a testing purpose, but I'm heads down
trying to write.

+PaulB -- any idea why these are gone? Can we add them back in.

Meggin

**Comment by pbakaus** [comment]
I'm on it!

**Comment by pbakaus** [comment]
So I don't actually know what's causing this and appreciate any help :( It works locally.

**Comment by pbakaus** [comment]
@petele probably something we could need your help with. It's pulling in the HTML wrapper just fine on a local machine, but decides to skip the wrapper.tpl (for whatever reason) when deployed. Thoughts?

**Comment by petele** [comment]
it's serving those files as plain text because when the files are built, there is no extension on the file. The permalink attribute needs to include `.html`, otherwise it will create a filename without an extension. DevSite serves files without an extension as plain text.

Compare https://raw.githubusercontent.com/google/WebFundamentals/master/src/_langs/en/updates/2015-05-19-cycle-through-editing-locations.markdown to https://raw.githubusercontent.com/google/WebFundamentals/master/src/_langs/en/updates/2015-05-08-go-to-a-line-number-at-a-specific-column.markdown

**Comment by pbakaus** [comment]
Great catch, thanks @petele. I fixed the remaining permalinks and updated the admin scraper so it won't happen again.
