### ISSUE TITLE
Incorrect hreflang implementation

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1434]
> To: Webmaster of https://developers.google.com/web/fundamentals/,
>
> Google has detected that some pages on your site have implemented the rel-alternate-hreflang tag incorrectly. In particular, there seems to be a problem with incorrect language and region codes, or incorrect bi-directional linking (if page A links with hreflang to page B, there must be a link back from B to A as well). Google uses the hreflang attributes to serve the correct language or regional URL to the right users in search results.

> Until you correct the errors on the hreflang links, your website will not benefit from additional language or region targeting.

See https://www.google.com/webmasters/tools/i18n?siteUrl=https://developers.google.com/web/fundamentals/ for report

**Comment by petele** [comment]
@gauntface - we'll need to verify this works properly

**Comment by gauntface** [comment]
I think this is in part to us being bad at managing our URLs. But this is a guess because I don't really understand the docs:

' Missing return links: annotations must be confirmed from the pages they are pointing to. If page A 
' links to page B, page B must link back to page A, otherwise the annotations may not be interpreted 
' correctly. 
For each error of this kind we report where and when we detected them, as well as where the return link is expected to be.

For the page: /device-access/
We have the following urls referenced in the head:

    <link rel="canonical" href="https://developers.google.com/web/fundamentals/device-access/">

    <link rel="alternate" hreflang="en" href="/web/fundamentals/device-access/index.html?hl=en">
    <link rel="alternate" hreflang="es" href="/web/fundamentals/device-access/index.html?hl=es">
    <link rel="alternate" hreflang="ja" href="/web/fundamentals/device-access/index.html?hl=ja">
    <link rel="alternate" hreflang="ko" href="/web/fundamentals/device-access/index.html?hl=ko">
    <link rel="alternate" hreflang="pt-br" href="/web/fundamentals/device-access/index.html?hl=pt-br">
    <link rel="alternate" hreflang="ru" href="/web/fundamentals/device-access/index.html?hl=ru">
    <link rel="alternate" hreflang="zh-cn" href="/web/fundamentals/device-access/index.html?hl=zh-cn">
    <link rel="alternate" hreflang="zh-tw" href="/web/fundamentals/device-access/index.html?hl=zh-tw">

Things to notice:

These pages reference the URL with index.html, rather than the canonicalised version of the URL. I've tried addressing this issue by creating canonical_url and relative_url which are added to every page as a variable.

The current href lang now looks like this for an example wrong:

    <link rel="canonical" href="http://localhost:7331/web/fundamentals/guides/your-first-multi-screen-site/content">

    <link rel="alternate" hreflang="en" href="http://localhost:7331/web/fundamentals/guides/your-first-multi-screen-site/content" />
    <link rel="alternate" hreflang="ar" href="http://localhost:7331/web/fundamentals/guides/your-first-multi-screen-site/content?hl=ar" />
    <link rel="alternate" hreflang="de" href="http://localhost:7331/web/fundamentals/guides/your-first-multi-screen-site/content?hl=de" />
    <link rel="alternate" hreflang="es" href="http://localhost:7331/web/fundamentals/guides/your-first-multi-screen-site/content?hl=es" />

Notice canonical and english are the same and that all URL's are canonical. 

One concern I have is that we are allowing requests such as:

/web/fundamentals/guides/your-first-multi-screen-site/content
/web/fundamentals/guides/your-first-multi-screen-site/content.html
/web/fundamentals/guides/your-first-multi-screen-site/content/index
/web/fundamentals/guides/your-first-multi-screen-site/content/index.html

These are all the same document. The canonical url will be the same for each but they all mark the alternatives for the URL and those URL's won't then

**Comment by gauntface** [comment]
Moving this MDL v2 - until it's launched I can't tell what web master tools will make of it.

**Comment by petele** [comment]
I **think** this is fixed, WMT is no longer yelling at us.
