### ISSUE TITLE
Style _includes/fundamentals/section_toc.liquid

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1630]
Should look something similar to related_guides.liquid but needs to fit at the bottom of each section.

**Comment by gauntface** [comment]
Just committed this in https://github.com/google/WebFundamentals/commit/f63475294f4e138d68070b2798c6f32214248033

Not sure what to put as the title (If I should put a title at all).

I've also had to drop the section heading from related guides because it doesn't make much sense for section table of contents (it'll be the same everywhere).

<img width="1185" alt="screen shot 2015-09-11 at 11 07 10" src="https://cloud.githubusercontent.com/assets/139760/9818248/88b30834-5875-11e5-9baf-ea3900815b0f.png">

**Comment by petele** [comment]
Looks good!
