### ISSUE TITLE
Tools: Main template broken or incomplete

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#1793]
Compare https://developers.google.com/web/tools/?hl=en to https://material-dot-web-central.appspot.com/web/tools/

* What's new link is missing, leading to the updates section.
* Projects need to be at top, heading is unnecessary imho
* Tips are missing
* Typography of guides list is all over the place, wastes lots of space
* Choice to have projects and part of guides above the fold was deliberate, please bring back.

**Comment by gauntface** [comment]
- "What's new link is missing, leading to the updates section." At the moment we are figuring out with what the plan is for DevTools in Updates. When that is fixed we can figure out if / how to link the two up.
    Personally I'd like to see DevTools posts / tips moved into Tools. Not sure what your or @petele's thoughts are on this.

- Project at the top - This didn't make much sense to me, if you are a user coming to this site for the first time, is the primary use for the tools section to point them off to some other site with little to no context? I would have thought the Tools content would be primary. @petele did you change it to be up top?

- Removal of tips was to reduce the number of things on the page, plus the gif's are super distracting.

- Typography - this is just straight out of MDL so any PR's / recommendations would be super appreciated. (In the short term I'll take a look now)

- Please see previous notes regarding projects. Why is it prioritised above the fold?

**Comment by petele** [comment]
Replaced by #1809

**Comment by petele** [comment]
From @pbakaus 

@gauntface to answer your questions from the closed ticket:

* I don't think a seperate blog for DevTools specific content is a great idea. I think we should keep them in the Updates section.
* Projects are at top as the main purpose of this entry site is to point to the sub pages for our projects. Surfacing the DevTools page is extremely important. If you have a better idea on how to achieve it, I'm all ears.
* Re: Tips: "I removed this because the page is busy" reminds me of these mobile sites that become super useless but nice looking, as too many features from the Desktop site are gone. We need those tips. We can absolutely try to make them look nicer and not as busy, but we need them.
* Will help with typography! I'll get a PR ready in the next few days.
* Design of the Tools page went through dozens of iterations and under careful consideration, we wanted the entry point for all of our tools be super easy, but also quickly have viewers realize there's more, i.e. the guides.
