### ISSUE TITLE
Tools landing page work

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1809]
- [x] Move google projects up to the top
- [x] Include guides list on page
- [x] What's new button in header should link to latest tools updates

**Comment by pbakaus** [comment]
@gauntface do answer your questions from the closed ticket:

* I don't think a seperate blog for DevTools specific content is a great idea. I think we should keep them in the Updates section.
* Projects are at top as the main purpose of this entry site is to point to the sub pages for our projects. Surfacing the DevTools page is extremely important. If you have a better idea on how to achieve it, I'm all ears.
* Re: Tips: "I removed this because the page is busy" reminds me of these mobile sites that become super useless but nice looking, as too many features from the Desktop site are gone. We need those tips. We can absolutely try to make them look nicer and not as busy, but we need them.
* Will help with typography! I'll get a PR ready in the next few days.
* Design of the Tools page went through dozens of iterations and under careful consideration, we wanted the entry point for all of our tools be super easy, but also quickly have viewers realize there's more, i.e. the guides.

**Comment by petele** [comment]
Issues listed fixed in #1822
