### ISSUE TITLE
Animation logic needs to be ported to material-design

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#1890]
@pbakaus's animation stuff is potentially necessary for animations.

**Comment by gauntface** [comment]
Can you share more docs about what this is? @petele @pbakaus

**Comment by pbakaus** [comment]
In the DevTools docs, as well as in the update section, we have the need to embed automatically running animations in some places that show a certain feature.

Animated gifs are big, have low frame rates to manage size and limited colors, plus eat a lot of memory and CPU power on mobile. The canvas based approach we've used in the old DevTools docs was efficient but a lot of JS, and every animation needed a script.

The solution I ended up implementing is the most simple I could come up with: Normal videos on the page and a small amount of JS that detects if you're on desktop, then hides the controls, sets loop to true and autoplays a video as soon as it comes into the viewport (and stops others). This ensures that your bandwidth isn't eaten and you always see the right animation running. On mobile, said logic simply does not run, and so you get normal videos that can be played back on demand.

**Comment by kaycebasques** [comment]
+1

**Comment by gauntface** [comment]
Personally not ok with the data hit on users especially considering serving
up mp4s isn't going to use adaptive streaming.

Is YouTube an option?

auto-play still seems like a stretch to me. I think We've had reports of
people suffering from regularly migraines when landing on a page with lots
of moving images (don't know if this was a gif or a video however)

**Comment by pbakaus** [comment]
The migraine issue came from the tips section where we've had lots of animated gifs at the same time. It was not about the video animations.

The original script for the animations was carefully designed with performance in mind. It never ran on mobile and would always only auto-play a video that's currently in the viewport. Thus, the only data hit on users happens when they *actually* scroll to the video and want to see it on a *Desktop* computer (with the exception that the browser might do some funky preloading).

If YouTube can auto-play and loop then it might be an option but I worry that the overhead on page performance compared to a single video tag is significant. Would require the YT API to control playback etc.

Needless to say, I've given this a lot of thought.
