### ISSUE TITLE
Updates: News & DevTools as sub categories in the menu is very odd

### ISSUE THREAD

**Issue by pbakaus** [google/WebFundamentals#2040]
In the sub menu, we currently have "DevTools" and "News" as seperate entries. This doesn't make much sense, as DevTools obviously includes lots of news.

**Comment by petele** [comment]
What would you suggest as an alternative?

**Comment by pbakaus** [comment]
Meggin is correct in that we're putting filters into the side menu here instead of hierarchal navigation, which doesn't make a lot of sense (in my earlier version of the Updates section, it wasn't an accident that most filters lived outside of the menu on the page).

I suggest the following:
- Remove News / DevTools from sidebar
- Make DevTools a tag
- Add the tags to the overview page as a way to filter, remove from sidebar

DevTools as a tag is sufficient for me, enough to be able to link to just DevTools content.

**Comment by petele** [comment]
Merging @Meggin's comments from #1857 to centralize the discussion:

> The Updates section as a new filter by tag. However, when you go to a page based on a selected filter, you can't see it's related tags. Arthur Evans actually spotted this-- I'm just raising the issue for speedy sake.

**Comment by gauntface** [comment]
Just a little background of why I removed it:

- The tags page didn't seem to get much traffic in the grand scheme of things
-  The structure of the tags didn't make much sense to me (i.e. clicking spotlights + Chrome DevTools) lead to an empty page: https://developers.google.com/web/updates/chrome-devtools/spotlight/
- (Personal one) I'm not a huge fan of DevTools updates being merged with blog posts

In my mind the New and DevTools posts are distinctly different.

I'm fine toying with the high level nav and for me, MVP would be to just have news (or some other name) and devtools as top level sections, no notion of tags until we figure out what we want to do with them and we have briefly discussed the idea of adding tags across all of Web Fundamentals which could then enable you to pull in pages related to a tag.

**Comment by pbakaus** [comment]
1) Fair enough.
2) Those weren't tags, but types of news and associated products. But yes, spotlights in there was a little experimental.
3) I'm intrigued to hear how you come to the conclusion that nothing about DevTools is newsworthy. I could understand if you think the tips aren't really news, but the digests? Really?

**Comment by gauntface** [comment]
Regarding 3) I'm not saying "nothing about devtools is newsworthy". The sheer amount of content that has been dropped into updates means it's hard to seperate web platform updates from DevTools Tips (See the 50/50 split of devtools and news https://developers.google.com/web/updates/pages/2).

I couldn't tell you the difference from digest and devtools tips because I've clumped them all together mentally and I can't differentiate them from the home page.

Bringing this back on topic - 'News' and 'DevTools' are now nothing more than "special" tags that are promoted to the sidenav.

@pbakaus @petele @Meggin @PaulKinlan what do we think of this approach of seperating out the devtools tips? If we agree it makes sense cool, what do we name it? If we don't, then shall we just drop the nav and stick to justy filter by tags in the sidenav?

**Comment by pbakaus** [comment]
OK thanks for the clarification. It sounds like the Digests are not the problem (they happen once per month), but the tips are.

Another option is to remove the tips and move them entirely to the Tools section. That would remove them from the RSS feed and traffic that the Updates section, and we could use them in different ways, i.e. include them in places where they make sense. The date driven approach doesn't make a lot of sense for tips anyway.
