### ISSUE TITLE
/web/updates/ UI / URL Feedback

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#2073]
There have been some comments on the current structure of /updates/, ignoring the folder structure of the written content and focusing on the UI / built site, the main points to figure out are:

1.) Should DevTools & News articles be mixed on the home page /web/updates?
2.) When you click on a post, should the URL contain news / devtools inside of it?
3.) Should News and DevTools be accessible in such a way that you can list just News or DevTools posts? If so - is the current URL ok?

**Comment by PaulKinlan** [comment]
Thinking about it, the old one was 1, and then the opposite of 2 and 3...  in that all posts were accessible under /updates/YYYY-MM/post-name but listed on many pages: updates/ listed *all* of the updates regardless of post, /updates/chrome is web, updates/chrome-devtools is just for dev-tools.  
So similar to 1.  I don't intend for there to be many more categories (pretty sure pete doesn't either) so how hard it is to have 1?

re:1 if we can, yes I think we should.

re: 2. I don't think in practice the public care.  It is just how you filter the feeds from the list and navigate to the previous and next articles.

re: 3 - Just to be upfront, I like the internal directory structure we now have in the new world for creating the content, I don't think we need to see it when published. unless it makes it easier to go next and previous and keep the context.

Assuming we have to have directories for the categorisation then we need a sub-folder for web so rather than "news", I wonder if we should have "chrome" or "platform"

**Comment by gauntface** [comment]
I've altered the URLs to be lower case.

I've also dropped the 'Filter by Tag' for subsections - didn't make much sense to have them.

I don't think we can drop 'news' from the url name unless we completely change the way we structure our content OR we change the way we build the subsections, largely because if the final file structure moves news into the root of updates, you can't then have the seperate section filters.

What we could do, is have news and devtools to be sections that the Updates Generator just munges into a single pool of files and then we have filters in the side menu which are preselected tags ('News' and 'DevTools' in this case).

**Comment by gauntface** [comment]
@petele when you read this, these changes are in this PR: https://github.com/google/WebFundamentals/pull/2074 Accept or close at your discretion.

**Comment by gauntface** [comment]
Spoke to Pete, current strategy:

1. Remove news and devtools from the urls
2. Remove the news / devtools folders, if they aren't being used for anything then they are pointless. Move the post files to /posts
3. Use tags as a way of filtering out what is displayed in the left hand side nav.

Sound good to everyone @PaulKinlan @petele?

**Comment by petele** [comment]
LGTM - folders were there simply to provide a way to separate content between different sections.

On the left nav, I'd like to see News and DevTools, open to others, but those are my primary.

Because of the URL change here, I suggest we hold the launch of v1 until this work is complete.

**Comment by gauntface** [comment]
+1 holding off on launch and that was going to be my intention. Will add a way to prodive a menu friendly name for the tags i.e. News and DevTools.

**Comment by PaulKinlan** [comment]
As long as there is something that paulb can point to for devtools news all
seems good.

**Comment by gauntface** [comment]
Added in support for this but we need the DevTools and News articles to have tags setup.

**Comment by petele** [comment]
Added the tags, I think we're good here!
