### ISSUE TITLE
[EN] Feedback for: /web/fundamentals/?hl=en

### ISSUE THREAD

**Issue by lenikirilov-taulia** [google/WebFundamentals#2187]
https://developers.google.com/web/fundamentals/?hl=en

This pages description contains a duplicate phrase "the right the right"

**Comment by PaulKinlan** [comment]
Hi @lenikirilov-taulia thanks for the report.  This looks like it was fixed in https://github.com/google/WebFundamentals/commit/b9051628ec500e74bd8ef488c33641c93ae00757 and we are just waiting for a deployment to happen.  

I will close this issue and ping @petele or @gauntface to see if they can kick-off the process.
