### ISSUE TITLE
[EN] Feedback for: /web/shows/new-in-chrome/?hl=en

### ISSUE THREAD

**Issue by bolvaritamas** [google/WebFundamentals#2189]
The embedded YouTube video can't go fullscreen. :(

**Comment by petele** [comment]
I think this should be fixed with #2193

**Comment by gauntface** [comment]
I doubt those changes will actually affect this.

Not sure why fullscreen is blank and not sure why it has the header and side bar.

**Comment by gauntface** [comment]
Looking at this - it might be an MDL issue.

It looks like the iframe is getting a ridiculous height awarded to it in full screen - initially I thought it was completely broken, but looking at this on my vertical screen, half the video is visible at the bottom of the screen.

**Comment by gauntface** [comment]
cc @sgomes as an FYI.

Looked at this again, I'm not sure what the solution should be.

I'm partly wondering if this is an issue with the layout again. If you set the height of the body to 100% you get the video iframe filling up the space of the screen in full screen, but you can still scroll down to reveal that the video is just covering some content and revealing the rest.

I'm not sure what more to do / debug. I suspect fixing layout.js in MDL to use fixed headers and not manipulate the DOM might make this problem go aware.

For now I'm going to remove fullscreen feature since it simply doesn't work.

**Comment by gauntface** [comment]
@sgomes found the fix for this.

will-change: translate is causing everything to go wonk. I've reverted this for just shows.
