### ISSUE TITLE
Anchors do not work - page gets scrolled to the top

### ISSUE THREAD

**Issue by kdzwinel** [google/WebFundamentals#2253]
There is a direct link in the DevTools Network panel to this page:

https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/resource-loading#resource-network-timing

When I clicked it:
<img width="835" alt="screen shot 2015-10-29 at 15 28 28" src="https://cloud.githubusercontent.com/assets/985504/10821257/bef66ca4-7e51-11e5-8320-068ffff16ff7.png">

Page loads at the correct scroll position just to go back to the very top as soon as 'load' fires.

I can reproduce it every time in Chrome Canary and Firefox, for some reason I can't reproduce it in Stable Chrome.

Maybe it's related with the Dev Summit ad somehow?

**Comment by gauntface** [comment]
I think this is an issue with MDL's layout module playing with the DOM.

cc @sgomes do you agree? (Disabling JS causes it to work).

**Comment by sgomes** [comment]
@gauntface It could be a problem with the layout module, yes, but it seems to work on anchors in https://getmdl.io. It may need some further investigation.

**Comment by Garbee** [comment]
@sgomes It is because [we handle it internally](https://github.com/google/material-design-lite/blob/master/docs/_assets/components.js#L52). Out default layout is broken in this regard. But due to it all being one big magic hack, not much we can do until 2.0 when it is all removed.

**Comment by kaycebasques** [comment]
@Garbee @gauntface what's the status on this? This one is big for me. DevTools docs rely heavily on cross-links.

**Comment by Garbee** [comment]
1.1 is out and we are now working towards 2.x. However, it is going to be a slow  process. About 2 months or so for even a beta type thing iirc. Even when MDL 2 does release, the site here will need a major overhaul since it is going to have many breaking changes.

Timing estimate could be off, but  needless to say we are taking our time to update everything so we do as little for developers as required and improve the overall codebase quality.

**Comment by Garbee** [comment]
One possible resolution that could be implemented in user-land I just thought of...

Listen for the `mdl-componentupgraded` event. Check if the event is for layout (since this would be post-upgrade.) If it is for layout, check the URL for a fragment. If a fragment is found, check the DOM for any IDs matching the fragment. If found, do a scroll to that identifier within the `mdl-layout__content` area.

Nasty that developers need to do this manually, but should be naturally fixed with whatever our new Layout setup is.

**Comment by kaycebasques** [comment]
riddle me this, @Garbee... it works on localhost

https://giphy.com/gifs/xT9DPizVMHZxFo8VKo

**Comment by Garbee** [comment]
I honestly have no clue. Sometimes it works but most of the time it doesn't.

**Comment by petele** [comment]
This should be fixed now. Sorry about that!!
