### ISSUE TITLE
MDL is not displaying maximized videos properly

### ISSUE THREAD

**Issue by sjamthe** [google/WebFundamentals#2325]
If I try to maximize the video on this page https://developers.google.com/web/tools/chrome-devtools/
it gets chopped of due to the frame on the left site.

It is ironic that the video talk about layout and this page gets it wrong.

**Comment by Garbee** [comment]
This is an upstream issue with Material Design Lite it appears. Due to how we implemented the Layout component to try and handle as much of the MD guidance for developers as we could.

V2 of MDL will be fixed by default since we are dropping the "magic handling" of stuff for developers. Until that lands and then this site is rewritten, the only real solution is rewriting the layout stuff internally.

**Comment by petele** [comment]
Thanks for the feedback, we've got an update coming next week that should fix this.
