### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/debug/snippets/#map-snippets-to-external-files-via-workspaces

### ISSUE THREAD

**Issue by rhbecker** [google/WebFundamentals#2403]
The [Map Snippets to external files via Workspaces](https://developers.google.com/web/tools/chrome-devtools/debug/snippets/#map-snippets-to-external-files-via-workspaces) section states: "you can map your Snippets to external files using Workspaces".

No details are provided on how to accomplish that - not on this snippets focused page, nor the linked [Workspaces page](https://developers.google.com/web/tools/setup/setup-workflow).

I'm able to add a host directory as a workspace on the "Sources" tab:

1. open "sources" tab
2. right-click and select "Add folder to workspace"
3. browse for host directory and click "ok"

Right-clicking within the "Snippets" tab reveals only a single context menu item: "New" for creating a new snippet file. There's no option to add a workspace from this tab.

So, perhaps you add the workspace via the "Sources" tab and then somehow make the contents of that workspace available to the "Snippets" tab? I've not figured out how to accomplish this.

**Comment by Garbee** [comment]
cc @kaycebasques 

Since you are listed as the author of the article, why is this section in there? I'm not seeing any way to map Snippets to a workspace. LocalStorage items aren't stored as files. And looking at the DevTools localstorage they aren't saved in there either.

Perhaps they got moved when the shift happened to persist things across incognito profiles. Either way, looks to me like this section needs to be removed since it doesn't seem possible.

**Comment by sbougon** [comment]
Ahhh ! thanks @Garbee ! I spent so much time googling around to find out if I was crazy or the doc was not correct, as I could not achieve this (mapping a snippet to a file system). Can wait for this to work as it would speed up the dev of various complex snippets and bookmarklets.

**Comment by Garbee** [comment]
@sbougon This isn't like "docs are ahead of implementation". This section seems to be outright incorrect. There is no way (as far as I can tell) for snippets to be mapped to the file system, nor is it planned.

The action here is to figure out if I'm nuts and it is possible, if so update docs to walk people through it. If I'm sane, then the section needs removal since it is misleading about what we provide.
