### ISSUE TITLE
[EN] Feedback for: /web/tools/chrome-devtools/?hl=en

### ISSUE THREAD

**Issue by NathanDaugherty** [google/WebFundamentals#2592]
The new Dev tools now has a menu I have to click into to set how the dev tools window is laid out, whereas before I could switch between the last two layouts with just one click. The icon took up hardly any room, but now I have to click again. great. thanks. I guess you're trying to be like the mobile Chrome app, which also puts everything inside a menu. I just don't understand why these design mistakes are made from such a smart company like Google.

**Comment by Garbee** [comment]
Thanks for the feedback. However, issues with the DevTools itself should go to the [chromium issue tracker](https://crbug.com). This is for documentation-specific issues.

This change was made since finding the alternate layout modes was hard to discover for users. The vast majority of users didn't know multiple modes existed. In order to make all the modes more discoverable as well as have room for more tooling to be made more accessible, the overflow menu was created. While some users, such as yourself, see this as a negative since you need to do more work it does create a better experience for the majority of users.
