### ISSUE TITLE
Update GeoLoc docs to mention getCurrentPosition is deprecated

### ISSUE THREAD

**Issue by aaldao** [google/WebFundamentals#2844]
Hello guys,

i have a porblem with the returned error in the getCurrentPosition function. The error code is the same that when you block the popup and when the function is deprecated. I have a problem with the https certificate because is not handled by me, and i need handle  differents cases when you block and when the function is deprecated.

Actual result: 
1 - Deprecated error callback:
PositionError {code: 1, message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."}
2 - Block error callback:
PositionError {code: 1, message: "User denied Geolocation"}

Expected result: Differents codes in the error object.

**Comment by PaulKinlan** [comment]
Will update the articles to provide guidance, but you are going to have to check the message string because iirc code:1 is still the correct code to use as per spec: https://dev.w3.org/geo/api/spec-source.html#position_error_interface.

It might be worth raising a bug on the spec to see if it is worthwhile getting a spec change and then a browser level change.

**Comment by PaulKinlan** [comment]
Started to document it in https://github.com/google/WebFundamentals/pull/2861

**Comment by aaldao** [comment]
What about next line if you change language?

failure.mode.indexOf("Only secure origins are allowed") == 0

**Comment by PaulKinlan** [comment]
I actaully made a mistake on that, it is message.  However I don't believe
we localize those console messages.

**Comment by petele** [comment]
Comment was already added.
