### ISSUE TITLE
Contributor picture isn't displayed on translated pages

### ISSUE THREAD

**Issue by joshua1988** [google/WebFundamentals#3173]
After checking with the image file name and contributors.yaml file to match both, the profile picture on the translated page doesn't show up. FYI, my id is "captainpangyo" and the image file name is "captainpangyo.jpg". 
Just another thing, to make sure, is the image folder path "src/statics/imgs/contributors"??

@petele - here we go.

**Comment by petele** [comment]
I SEE YOU! https://developers.google.com/web/fundamentals/primers/service-worker/cache-and-return-requests?hl=ko

I spent 20 min banging my head on my desk this morning trying to figure out why it wasn't work. It worked locally, in staging, everything. Due to a small change in DevSite (the app that hosts all our docs within Google), KO and JA files weren't being published. 

I've updated our deployment process and JA and KO files are now being properly deployed.

**Comment by joshua1988** [comment]
@petele - Nicely done! Thank you for taking your time out to resolve this bug. I really appreciate it!
There is actually another thing that I would like to ask you to do. I know you are the one in charge of this Web Fundamental repository and I just got started translating another Google Project's document called HTML5Rocks as you see [here](https://github.com/html5rocks/www.html5rocks.com/pull/1442).

Would it be okay to ask you to merge this document? or Do you have any clue who's in charge of this repository? It would be very appreciated :) 

Thanks a lot! @petele

**Comment by cwdoh** [comment]
@joshua1988, usally @PaulKinlan maintains it, and we also had a support board on trello for html5rocks korean translator. :) I have added you. see Trello board HTML5Rocks/ko - https://trello.com/b/KF7tY7Yi/html5rocks-ko.
