### ISSUE TITLE
Setup PR staging for DevSite infrastructure

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#3330]
Should stage for PR's when submitted

**Comment by x1ddos** [comment]
@petele what is the target branch which will become master and which needs staging PRs?

I suspect it is `next-version`. If it is, FYI: this will be complicated as the server part is very different now. Previously, this was possible because of a special server I wrote: https://github.com/google/WebFundamentals/tree/master/tools/server.

**Comment by PaulKinlan** [comment]
Given our hosting is just a local appengine instance now, it feels like we could just run the dev server that Pete has created and stage that.  It's not a million miles away from what we used to do....

**Comment by PaulKinlan** [comment]
Actually, now that I say that I remember that one of the things the server did was allow us to deploy unlimted versions of the site, which we won't get if we fall back to the older way again.

**Comment by petele** [comment]
Can we not deploy next-version to next-version (which would be the default version), and then deploy PRs to other versions? Then you'd be able to do https://pr1234.web-central.appspot.com to see that PR? and web-central.appspot.com to see what's in next-version?

**Comment by x1ddos** [comment]
@petele the issue is what @PaulKinlan said: you can't have unlimited number of versions. That was the whole point :) and also how staging PRs actually worked. It didn't create/upload new GAE versions, only new content to GCS buckets, and then the server knew which bucket to serve the content from based on the request host (e.g. pr1234 served from a pr1234 GCS bucket).

btw, you can't use https://version.appspot, you'd need to do https://version-dot-appid.appspot.com

**Comment by x1ddos** [comment]
Looking a bit more into the next-version branch, I can see there's a [gae folder with a few templates in it](https://github.com/google/WebFundamentals/tree/c5e74d03603ba3a497432e9be88ba2d41acfbda5/gae).

Because the [library](https://github.com/google/weasel) to support "unlimited versions" serving staged PRs is written in Go, the WebFundamentals local server would need to be written in Go, too. I think I could try doing it, unless those Python scripts are also used for prod devsite, then it wouldn't make much sense.

One nice side effect of having local server in Go is you wouldn't even need to have people downloading and installing GAE SDK or its dependencies (e.g. markdown). They could just use a single self-sufficient pre-built binary, but again, unless some of that stuff is also used for prod devsite.

**Comment by x1ddos** [comment]
Specifically, I'm talking about re-using https://github.com/google/WebFundamentals/tree/master/tools/server.

**Comment by petele** [comment]
All told, the server is about 750 lines of python (including comments, etc). My biggest concern in moving it to Go is that I don't know Go at all, and not sure how much experience there is on the team, so if something needs to be fixed, we'd be at a disadvantage, either having to figure out Go or ask you.

Let's split this into two issues:
1. Deploy next-version (without) PRs to web-central.appspot.com 
2. Deploy PRs to a staging server. 

Let's focus on the first item, then over the next couple of weeks we can figure out how to do the second without too much pain. 

@PaulKinlan, does that work for you?

**Comment by PaulKinlan** [comment]
Sgtm

**Comment by petele** [comment]
OK - i'm going to close this one and open two new ones. I'll reference this one in the new ones.
