### ISSUE TITLE
Working with Promises

### ISSUE THREAD

**Issue by addyosmani** [google/WebFundamentals#3447]
ILT content: https://docs.google.com/document/d/1H3GaE6JQhydNaPzII9hgGZL-uL73VvgQ02FYijeK0js/edit#heading=h.6nas0edx1hn3

Jake's canonical Promises article that has been recently migrated over: https://developers.google.com/web/fundamentals/primers/promises/?hl=en

Is there anything covered in the textbook worth bringing over or does the primer we have right now capture all the best parts?

**Comment by addyosmani** [comment]
@sgomes do you think you'll have time during this hackathon week to audit the current Promises article and make a call on whether there's anything missing that's present in the ILT content?

**Comment by sgomes** [comment]
@addyosmani The primer seems to cover everything, even though it's organised differently. It also expands on concepts like interactions with generators, which the ILT content doesn't cover.

If we want tutorial-type content (and I think we do, since that seems to be the preference on WF), I suggest using Jake's article as-is. If we want reference content, however, the ILT stuff would be a better fit.

**Comment by sgomes** [comment]
Closing, as I don't think there's any action needed, but feel free to reopen and reassign to me if you disagree.

**Comment by addyosmani** [comment]
@sgomes Thank you for evaluating the content and making a call on whether it needs to be landed. Glad to hear our bases are all covered 👍
