### ISSUE TITLE
Comment widget not saving new comments

### ISSUE THREAD

**Issue by petele** [google/WebFundamentals#3754]
I'm investigating, not sure what's going on. Looks like it's not just a problem with our site, but it's happening on other sites as well.

**Comment by simevidas** [comment]
I’ve encountered this issue: I’ve posted a comment to [this post](https://developers.google.com/web/updates/2016/10/css-hyphens) yesterday, but it doesn’t appear in the comments box. My comment is available [on Google+](https://plus.google.com/+%C5%A0imeVidas/posts/gMhxAnxQQjh) (because I have “Also share on Google+” enabled).

**Comment by petele** [comment]
This appears to be fixed now.
