### ISSUE TITLE
[Optimize Images / Helpful]

### ISSUE THREAD

**Issue by danielocdh** [google/WebFundamentals#5117]
What tool are you using to compress the compared images?
I don't want to depend on a web service.
What tool could be used by users with different operating systems?

Thanks

edit:
it just doesn't make much sense to me that the audit will say: you need to optimize this image because it can weight "this", but it doesn't tell you how it is making the image weight "this"

**Comment by malchata** [comment]
Command line tools are always great, because they can be compiled to work cross-platform and are often supported by major package managers (e.g., npm, brew, yum, chocolatey, et cetera).

For JPEGs I use: jpeg-recompress, guetzli, mozjpeg
For PNGs: pngquant, optipng, zopflipng
For GIFs: gifsicle
For SVGs: svgo

Most of these are installable through package managers (jpeg-recompress and svgo are npm installable, even).

That said, I used to be just like you and avoided web services, but Cloudinary's service is pretty awesome, if a little weird to grok how it all works at first.

-j

**Comment by danielocdh** [comment]
@malchata I'm ok using command line tools, as long as they are available everywhere not only linux. Thanks for the recommendations but I was more interested in knowing exactly which tools the audit uses, it just doesn't make much sense to me that it will say you need to optimize this image because it can weight "this", but it doesn't tell you how it is making the image weight "this"
