### ISSUE TITLE
Bug in PWA Training Core Technologies module

### ISSUE THREAD

**Issue by glennsimon** [google/WebFundamentals#5253]
![image](https://user-images.githubusercontent.com/1953290/32427229-2be423ac-c274-11e7-92cc-4ddbfa30f0d8.png)

See image above.  Typing the code in the console as directed did not work.  GET resulted in a 404 not found error, then parsing failed (I think).

Web page with the error: https://developers.google.com/web/ilt/pwa/core-technologies

**Comment by DavidScales** [comment]
Hey Glenn, in order for this demo to work, you would have to have the `animals.json` file on your local machine. What Sarah is doing is only intended to show the usage of the Fetch API. 

She has a directory on her computer with an `animals.json` file in it, and she is running a local server in that directory. When she runs the first part of the code, `fetch('animals.json')`, the browser requests and returns that `animals.json` file from her computer.

Since you don't have the file on your machine or a server running, you can't request the resource. It would be no different than if I ran `fetch('someThingThatDoesNotExist')` right now. That's why you're getting a 404 (because the file isn't found) as well as the parsing error (you can't parse a file that you don't have). 

Does that make sense? If you checkout the [Fetch API lab](https://developers.google.com/web/ilt/pwa/lab-fetch-api), it will provide you with the appropriate files and instructions on setting up a server, and walk you through using the Fetch API with multiple examples, including how to handle errors like 404's. I hope that helps!

**Comment by glennsimon** [comment]
Yes David, that makes sense.  I will checkout the Fetch API lab and try it again.  I was confused because in the video the speaker implied that I could try it in the devtools on the current page, so I thought that file was included with the page source.  She says that the file is in the core-technologies folder, but as you noted that folder does not exist on the page (when I look in sources on devtools).  Maybe I missed a requirement to install something earlier in the training.

I thought it was a bug because I thought the intent was to have that file available with the page so it could be fetched and displayed on the console.

Thanks for your help, and thanks for merging my first pull request (google-developer-training/pwa-training-labs)!

**Comment by DavidScales** [comment]
Ah yeah in that sense it is kind of a bug. If we get a chance to re-film in the future we can hopefully correct that. No problem, thanks for the fix and good luck learning about PWA's!
