### ISSUE TITLE
Recommend SW registration go in sep file

### ISSUE THREAD

**Issue by gauntface** [google/WebFundamentals#5717]
Recommend developers register service worker in a stand alone script on top of in window.onload to avoid dependency issues: https://www.loxodrome.io/post/service-worker-registration/

cc @jeffposnick 

Sidenote: Not sure if the same would apply if you just moved the SW reg to a seperate inline script tag.

**Comment by jeffposnick** [comment]
(Responding since @kaycebasques just assigned this to me.)

https://www.loxodrome.io/post/service-worker-registration/ returns HTTP 404 right now.

I think the guidance at https://developers.google.com/web/fundamentals/primers/service-workers/registration captures the most relevant points, regardless of where that code lives.

I'm going to close given the lack of context.
