### ISSUE TITLE
[Lighthouse / Blocking Resources / Helpful]

### ISSUE THREAD

**Issue by shakyjake** [google/WebFundamentals#5731]
**Page Affected:** 
https://developers.google.com/web/tools/lighthouse/audits/blocking-resources

**What needs to be done?**

The page offers no meaningful solutions to render-blocking, non-critical CSS. Consider adding some.

The page claims that the (non-standard) "disabled" attribute will prevent browsers from downloading stylesheets. This is not true for all browsers and should be removed.

**Comment by kaycebasques** [comment]
Thank you for feedback @shakyjake 

Yeah... that doc definitely has "room for improvement"

**Comment by kaycebasques** [comment]
Re: the `disabled` attribute I changed the phrasing to say that "some browsers won't download the stylesheet" when that attribute is present. I'm leaving it in the doc because it's [part of Lighthouse's algorithm](https://github.com/GoogleChrome/lighthouse/blob/01b4cb8390a2c92765555a2a467ab393956a94dc/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js#L67).

Can you file a bug at https://github.com/googlechrome/lighthouse/issues/new if you think that they should remove this check?

**Comment by kaycebasques** [comment]
I'm also noting that it's not supported in all browsers.

**Comment by kaycebasques** [comment]
Regarding meaningful solutions for CSS, I'm adding a mention to Addy's "critical" tool.
