### ISSUE TITLE
"What's New In DevTools (Chrome N)" should be "What's New In DevTools (Chrome N-1)"

### ISSUE THREAD

**Issue by takenspc** [google/WebFundamentals#8105]
**Page Affected:** <https://developers.google.com/web/updates/2019/09/devtools>, <https://developers.google.com/web/updates/2019/07/devtools>, and so on

[What's New In DevTools (Chrome 78)](https://developers.google.com/web/updates/2019/09/devtools)

- Chrome **77** introduces "Largest Contentful Paint" ([source](https://blog.chromium.org/2019/08/chrome-77-beta-new-performance-metrics.html)).
- Chrome **77** includes Lighthouse 5.2.0 ([source](https://github.com/GoogleChrome/lighthouse/releases/tag/v5.2.0)).

[What's New In DevTools (Chrome 77)](https://developers.google.com/web/updates/2019/07/devtools)

- Chrome **76** includes Lighthouse 5.1.0

**What needs to be done?**

- [ ] Pages titles should be corrected.
- [ ] Tags should be corrected.
- [ ] "Discover other DevTools features" section should be corrected.

**Comment by kaycebasques** [comment]
Thanks for the report.

The [New Performance Metrics](https://blog.chromium.org/2019/08/chrome-77-beta-new-performance-metrics.html) section of the Chromium blog post is announcing that the metric was implemented in Chromium. Support for the metric came to DevTools happened in 78, so that's "working as expected."

I'll spare you the details about Lighthouse but I can add a note to the post mentioning that 5.2 actually arrived in Chrome 77.
