### ISSUE TITLE
Chrome / Chromium DevTools issue - simulation of mobile

### ISSUE THREAD

**Issue by mdziczkowski** [google/WebFundamentals#8224]
I want to report a missing feature with can be counted in as a bug.

In there is a possibility to turn on the Mobile simulation function thru the DevTools, but there is no possibility to turn it off. Please fix it asap. Thanks

**Comment by connerturner** [comment]
You can toggle the mobile simulation/viewport off by selecting the "Toggle device toolbar" again, or pressing Ctrl+Shift+M. If you cannot do this then yes it seems to be a bug.

In that case, since it's not a bug with the WebFundamentals documentation then please file a bug at [crbug.com](https://crbug.com)
